#!/usr/bin/env bash
# Regression test: llms-full.txt must contain no mkdocs-relative links.
#
# The file is generated by concatenating the docs sources, which link each other
# the mkdocs way -- [CLI Reference](CLI.md). MkDocs resolves those at render
# time, but llms-full.txt is served at moav.sh/llms-full.txt, where the same
# link points at moav.sh/CLI.md and 404s. An agent handed the file follows it
# and gets nothing, with no error to notice.
#
# Tests the rewriter directly (fast, offline) and then the built artifact if one
# is present. Run scripts/build-llms-full.sh first for the full check.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
pass=0; fail=0
ok()  { printf '  ok    %s\n' "$1"; pass=$((pass+1)); }
bad() { printf '  FAIL  %s\n' "$1"; fail=$((fail+1)); }

echo "llms-full.txt link absolutization"

rw="$ROOT/scripts/absolutize-links.py"
[ -f "$rw" ] || { echo "  scripts/absolutize-links.py missing"; exit 1; }

r() { LLMS_BASE="https://moav.sh/docs" python3 "$rw"; }

# --- the rewriter itself -----------------------------------------------------
t() {  # <label> <input> <expected>
    local got; got=$(printf '%s' "$2" | r)
    [ "$got" = "$3" ] && ok "$1" || bad "$1: got [$got] expected [$3]"
}
t "plain page link"     '[CLI](CLI.md)'            '[CLI](https://moav.sh/docs/CLI/)'
t "link with anchor"    '[DNS](DNS.md#records)'    '[DNS](https://moav.sh/docs/DNS/#records)'
t "index becomes root"  '[Home](index.md)'         '[Home](https://moav.sh/docs/)'
t "hyphenated slug"     '[QS](quick-start.md)'     '[QS](https://moav.sh/docs/quick-start/)'
# Things it must NOT touch.
t "absolute untouched"  '[x](https://moav.sh/docs/CLI/)' '[x](https://moav.sh/docs/CLI/)'
t "bare anchor kept"    '[x](#section)'            '[x](#section)'
t "root-relative kept"  '[x](/assets/a.png)'       '[x](/assets/a.png)'
t "non-md kept"         '[x](image.png)'           '[x](image.png)'
t "empty label ok"      '[](CLI.md)'               '[](https://moav.sh/docs/CLI/)'

# --- the generator must use it ------------------------------------------------
if grep -q 'absolutize-links.py' "$ROOT/scripts/build-llms-full.sh"; then
    ok "build-llms-full.sh pipes each page through the rewriter"
else
    bad "build-llms-full.sh cats pages verbatim — relative links would ship again"
fi

# --- the built artifact, when present ---------------------------------------
out="$ROOT/site/llms-full.txt"
if [ -f "$out" ]; then
    rel=$(grep -oE '\]\([^)]+\)' "$out" | sed 's/^](//; s/)$//' \
            | grep -E '\.md($|#)' | grep -vE '^https?://' | sort -u || true)
    if [ -z "$rel" ]; then
        ok "built llms-full.txt has no relative .md links"
    else
        bad "relative link(s) in the built file: $(printf '%s' "$rel" | tr '\n' ' ')"
    fi
else
    echo "  note  site/llms-full.txt not built; skipped the artifact check"
fi

# --- nav and the generator's PAGES list must agree ---------------------------
# They are two hand-maintained lists of the same thing. A page added to the nav
# but not to PAGES is simply absent from llms-full.txt, with nothing to notice.
# Plain loop, no comm/process-substitution/nested heredocs -- an earlier version
# used all three and silently compared against an empty list.
gen_list=$(sed -n '/^PAGES=(/,/^)/p' "$ROOT/scripts/build-llms-full.sh" | grep -oE '[A-Za-z0-9_.-]+\.md')
nav_list=$(sed -n '/^nav:/,/^[a-z_]*:/p' "$ROOT/mkdocs.yml" | grep -oE '[A-Za-z0-9_.-]+\.md')
missing=""
for pg in $nav_list; do
    printf '%s\n' "$gen_list" | grep -qx "$pg" || missing="$missing $pg"
done
if [ -z "$missing" ]; then
    ok "every nav page is in the generator's PAGES list ($(printf '%s\n' "$nav_list" | wc -l | tr -d ' ') pages)"
else
    bad "in the nav but missing from llms-full.txt:$missing"
fi

echo ""
echo "  passed: $pass   failed: $fail"
[ "$fail" -eq 0 ] || exit 1
