#!/usr/bin/env bash
# Build site/llms-full.txt by concatenating the MkDocs sources in nav order.
# Run from the repo root after changing anything under docs/:
#   ./scripts/build-llms-full.sh
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="site/llms-full.txt"
BASE="https://moav.sh/docs"

# Nav order, mirroring mkdocs.yml.
PAGES=(
  index.md
  quick-start.md
  mission.md
  impact.md
  threat-model.md
  architecture.md
  protocols.md
  philosophy.md
  SETUP.md
  DNS.md
  DEPLOY.md
  CLIENTS.md
  client.md
  mahsanet.md
  CLI.md
  MONITORING.md
  TROUBLESHOOTING.md
  OPSEC.md
  development.md
)

{
  echo "# MoaV, full documentation"
  echo
  echo "> Complete MoaV documentation in one file, concatenated from the MkDocs sources in nav order."
  echo "> Short index: https://moav.sh/llms.txt"
  echo "> Source: https://github.com/MotherofallVPNs/moav-site"
  echo "> Generated by scripts/build-llms-full.sh, do not edit by hand."
  echo
} > "$OUT"

for page in "${PAGES[@]}"; do
  if [ ! -f "docs/$page" ]; then
    echo "missing docs/$page" >&2
    exit 1
  fi
  slug="${page%.md}"
  [ "$slug" = "index" ] && url="$BASE/" || url="$BASE/$slug/"
  {
    echo "---"
    echo
    echo "<!-- source: docs/$page | url: $url -->"
    echo
    cat "docs/$page"
    echo
  } >> "$OUT"
done

echo "wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes, ${#PAGES[@]} pages)"
